source=./land/defaults.conf # this needs to be sourced before theme file
source=./land/nvidia.conf

######################################################################################################
# uncomment if using hyprtheme and remove any other source for hyprtheme.conf
# source=/home/flicko/.config/hypr/themes/hyprtheme.conf

######################################################################################################
# MANUAL THEME SOURCE HERE

# $yorha=$HERE/themes/yorha
# source=$yorha/theme.conf

######################################################################################################

source=./land/general.conf
source=./land/binds.conf
source=./land/auto.conf
# source=./profiles/power.conf

animation = windows, 1, 2, popup, slide
animation = windowsOut, 1, 2, popup, slide
animation = fade, 1, 2, popup
animation = workspaces, 1, 3, default
