env = HYPRCURSOR_THEME,macOS
env = HYPRCURSOR_SIZE,24

input {
    touchpad {
        natural_scroll=$NATURALSCROLL
    }
}

general {
    col.active_border = rgba(d8d8d888)
    col.inactive_border = rgba(00000000)
    border_size = 3
    gaps_out = 10
}

dwindle {
    pseudotile=$PSEUDOTILE
}

gestures {
    gesture=$WORKSPACESWIPEFINGERS,horizontal,workspace
}

xwayland {
    force_zero_scaling=$XZEROSCALING
}

misc {
    disable_hyprland_logo=$DISABLEHYPRLOGO
    animate_manual_resizes=$ANIMATEDRESIZE
    animate_mouse_windowdragging=$ANIMATEDDRAG
}

decoration {
  rounding=5
  rounding_power=4
  inactive_opacity=0.9
  active_opacity=0.9

  blur {
    enabled=true
    new_optimizations=true
    size=9
    passes=2
  }
  shadow {
    enabled=true
    range=32
    render_power=2
    color=rgba(00000050)
  }
}

bezier = popup, 0.10, 0.9, 0.1, 1.05

layerrule {
  name = anim_for_wofi
  animation = popup
  # no_anim = on
  match:namespace = wofi
}
